### ISSUE TITLE
Laggy board UI while running engine

### ISSUE THREAD

**Issue by Lingepumpe** [franciscoBSalgueiro/en-croissant#530]
### Describe the bug

In the Analysis Board, if I have stockfish running as a engine and scroll through the game move by move the arrow keys, the board is laggy. Pieces stutter in the middle of their move animation, and in general just moving forward is slow because the move animation takes much longer.

The issue is not the general load on the PC, if I start a second en-croissant while the first has the engine running, then I can scroll through moves quickly and fluidly in the second version (unless I also turn on the engine there).

If somebody has an idea how to tackle this, I am willing to create a PR for this - I just don't know where exactly to start for this. I already implemented the ability to set a process priority for the engine process, but this didn't fix the issue.

### Reproduction

1. Open Analysis board
2. Make a few moves
3. Use left and right arrow keys  to scroll through the moves. Move animations are quick and smooth.
4. Start the engine to analyze along side.
5. Use left and right arrow keys  to scroll through the moves. Move animations stutter - they are slow and jerky or laggy.

### Platform and versions

Linux, tested on current git master.

### Stack trace

```Shell

```

**Comment by archimag** [comment]
I believe it's all about state management in react App (new information from engine calls re-rendering without real necessity). Frankly It should be fully rewritten though all app and will solve many other issues.

**Comment by Lingepumpe** [comment]
I have fixed this with a PR that reduces the amount of events created by the engine. Maybe not the approach you were suggesting @archimag - but it works and it makes using en-croissant much nicer for me. Here is how it behaves with my PR:

https://github.com/user-attachments/assets/a085d089-2a5d-4f6f-910b-5a5d20923222

**Comment by DarrellThomas** [comment]
This is the same root cause as #631, which is addressed by PR #725.

The stutter isn't caused by too many engine events crossing IPC — the Rust-side rate limiter (5 Hz via `governor`) was already in place when this issue was filed. The problem is the **cost per event** on the React side.

Between v0.11.1 and when this issue was filed, two commits moved per-cell logic from parent-computed props to individual store subscriptions:

- `e4ed430d` (Sep 2024) — added a per-cell `getTranspositions()` subscription that walks the entire game tree
- `f07a1348` (Dec 2024) — moved `isCurrentVariation` from a parent prop to a per-cell subscription

This turned every engine event into O(N) selector evaluations (one per notation cell). For a typical game with ~120 cells at 5 events/sec, that's ~1,800 `fast-deep-equal` comparisons per second on the main thread — directly competing with CSS animation frames.

PR #725 restores the v0.11.1 architecture: the parent subscribes once and passes cheap props down, reducing the per-event cost from 3N to ~3 per tree level.

@archimag's original comment was exactly right — it was a React state management issue causing unnecessary re-rendering work.

**Comment by uribracha2611** [comment]
Sorry to necro this, but I'm still experiencing the issue on the latest version (v0.15.0 AppImage in WSL 2 Ubuntu). Anything i can do?
